# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from common.v1 import common_pb2 as common_dot_v1_dot_common__pb2
from photo.v1 import photo_service_pb2 as photo_dot_v1_dot_photo__service__pb2


class PhotoServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/photoops.photo.v1.PhotoService/Health',
                request_serializer=common_dot_v1_dot_common__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.CreateUploadIntent = channel.unary_unary(
                '/photoops.photo.v1.PhotoService/CreateUploadIntent',
                request_serializer=photo_dot_v1_dot_photo__service__pb2.CreateUploadIntentRequest.SerializeToString,
                response_deserializer=photo_dot_v1_dot_photo__service__pb2.CreateUploadIntentResponse.FromString,
                _registered_method=True)
        self.CompleteUpload = channel.unary_unary(
                '/photoops.photo.v1.PhotoService/CompleteUpload',
                request_serializer=photo_dot_v1_dot_photo__service__pb2.CompleteUploadRequest.SerializeToString,
                response_deserializer=photo_dot_v1_dot_photo__service__pb2.PhotoAsset.FromString,
                _registered_method=True)
        self.ListPhotos = channel.unary_unary(
                '/photoops.photo.v1.PhotoService/ListPhotos',
                request_serializer=photo_dot_v1_dot_photo__service__pb2.ListPhotosRequest.SerializeToString,
                response_deserializer=photo_dot_v1_dot_photo__service__pb2.ListPhotosResponse.FromString,
                _registered_method=True)
        self.GetPhoto = channel.unary_unary(
                '/photoops.photo.v1.PhotoService/GetPhoto',
                request_serializer=photo_dot_v1_dot_photo__service__pb2.GetPhotoRequest.SerializeToString,
                response_deserializer=photo_dot_v1_dot_photo__service__pb2.PhotoAsset.FromString,
                _registered_method=True)
        self.ListPhotoSpacetime = channel.unary_unary(
                '/photoops.photo.v1.PhotoService/ListPhotoSpacetime',
                request_serializer=photo_dot_v1_dot_photo__service__pb2.ListPhotoSpacetimeRequest.SerializeToString,
                response_deserializer=photo_dot_v1_dot_photo__service__pb2.ListPhotoSpacetimeResponse.FromString,
                _registered_method=True)
        self.GetVariantsByIds = channel.unary_unary(
                '/photoops.photo.v1.PhotoService/GetVariantsByIds',
                request_serializer=photo_dot_v1_dot_photo__service__pb2.GetVariantsByIdsRequest.SerializeToString,
                response_deserializer=photo_dot_v1_dot_photo__service__pb2.GetVariantsByIdsResponse.FromString,
                _registered_method=True)


class PhotoServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUploadIntent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPhotos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPhoto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPhotoSpacetime(self, request, context):
        """Internal service-to-service read-RPC: the space-time + device attributes of
        the caller's `ready` photos, for clustering. Deliberately NOT gateway-exposed
        (no http annotation) and lean — it must not carry the gallery ListPhotos
        payload (variants, presigned urls). Consumed by cluster-worker.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVariantsByIds(self, request, context):
        """Internal batched owner-scoped variant resolution (session 019): given a set
        of photo ids, return each owned photo's variant views (short-lived presigned
        GET urls — variants only, NEVER originals). Non-owned / unknown ids are
        simply absent from the result. Consumed by api-gateway's public post route.
        Deliberately NOT gateway-exposed (no http annotation).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PhotoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=common_dot_v1_dot_common__pb2.HealthCheckRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.HealthCheckResponse.SerializeToString,
            ),
            'CreateUploadIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUploadIntent,
                    request_deserializer=photo_dot_v1_dot_photo__service__pb2.CreateUploadIntentRequest.FromString,
                    response_serializer=photo_dot_v1_dot_photo__service__pb2.CreateUploadIntentResponse.SerializeToString,
            ),
            'CompleteUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteUpload,
                    request_deserializer=photo_dot_v1_dot_photo__service__pb2.CompleteUploadRequest.FromString,
                    response_serializer=photo_dot_v1_dot_photo__service__pb2.PhotoAsset.SerializeToString,
            ),
            'ListPhotos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPhotos,
                    request_deserializer=photo_dot_v1_dot_photo__service__pb2.ListPhotosRequest.FromString,
                    response_serializer=photo_dot_v1_dot_photo__service__pb2.ListPhotosResponse.SerializeToString,
            ),
            'GetPhoto': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPhoto,
                    request_deserializer=photo_dot_v1_dot_photo__service__pb2.GetPhotoRequest.FromString,
                    response_serializer=photo_dot_v1_dot_photo__service__pb2.PhotoAsset.SerializeToString,
            ),
            'ListPhotoSpacetime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPhotoSpacetime,
                    request_deserializer=photo_dot_v1_dot_photo__service__pb2.ListPhotoSpacetimeRequest.FromString,
                    response_serializer=photo_dot_v1_dot_photo__service__pb2.ListPhotoSpacetimeResponse.SerializeToString,
            ),
            'GetVariantsByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVariantsByIds,
                    request_deserializer=photo_dot_v1_dot_photo__service__pb2.GetVariantsByIdsRequest.FromString,
                    response_serializer=photo_dot_v1_dot_photo__service__pb2.GetVariantsByIdsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'photoops.photo.v1.PhotoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('photoops.photo.v1.PhotoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PhotoService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photoops.photo.v1.PhotoService/Health',
            common_dot_v1_dot_common__pb2.HealthCheckRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUploadIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photoops.photo.v1.PhotoService/CreateUploadIntent',
            photo_dot_v1_dot_photo__service__pb2.CreateUploadIntentRequest.SerializeToString,
            photo_dot_v1_dot_photo__service__pb2.CreateUploadIntentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photoops.photo.v1.PhotoService/CompleteUpload',
            photo_dot_v1_dot_photo__service__pb2.CompleteUploadRequest.SerializeToString,
            photo_dot_v1_dot_photo__service__pb2.PhotoAsset.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPhotos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photoops.photo.v1.PhotoService/ListPhotos',
            photo_dot_v1_dot_photo__service__pb2.ListPhotosRequest.SerializeToString,
            photo_dot_v1_dot_photo__service__pb2.ListPhotosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPhoto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photoops.photo.v1.PhotoService/GetPhoto',
            photo_dot_v1_dot_photo__service__pb2.GetPhotoRequest.SerializeToString,
            photo_dot_v1_dot_photo__service__pb2.PhotoAsset.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPhotoSpacetime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photoops.photo.v1.PhotoService/ListPhotoSpacetime',
            photo_dot_v1_dot_photo__service__pb2.ListPhotoSpacetimeRequest.SerializeToString,
            photo_dot_v1_dot_photo__service__pb2.ListPhotoSpacetimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVariantsByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photoops.photo.v1.PhotoService/GetVariantsByIds',
            photo_dot_v1_dot_photo__service__pb2.GetVariantsByIdsRequest.SerializeToString,
            photo_dot_v1_dot_photo__service__pb2.GetVariantsByIdsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
