# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cluster.v1 import cluster_service_pb2 as cluster_dot_v1_dot_cluster__service__pb2
from common.v1 import common_pb2 as common_dot_v1_dot_common__pb2


class ClusterServiceStub:
    """Deterministic hierarchical clustering of a user's photos into an immutable
    tree. Clustering methods are pluggable behind a registry (SOLID): this slice
    ships `time_only`; space-time is a registered-later seam. Runs are async
    (result_id == async job id); see process.proto for the RabbitMQ contract.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/photoops.cluster.v1.ClusterService/Health',
                request_serializer=common_dot_v1_dot_common__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.ListClusteringMethods = channel.unary_unary(
                '/photoops.cluster.v1.ClusterService/ListClusteringMethods',
                request_serializer=cluster_dot_v1_dot_cluster__service__pb2.ListClusteringMethodsRequest.SerializeToString,
                response_deserializer=cluster_dot_v1_dot_cluster__service__pb2.ListClusteringMethodsResponse.FromString,
                _registered_method=True)
        self.GenerateClusters = channel.unary_unary(
                '/photoops.cluster.v1.ClusterService/GenerateClusters',
                request_serializer=cluster_dot_v1_dot_cluster__service__pb2.GenerateClustersRequest.SerializeToString,
                response_deserializer=cluster_dot_v1_dot_cluster__service__pb2.GenerateClustersResponse.FromString,
                _registered_method=True)
        self.GetClusteringResult = channel.unary_unary(
                '/photoops.cluster.v1.ClusterService/GetClusteringResult',
                request_serializer=cluster_dot_v1_dot_cluster__service__pb2.GetClusteringResultRequest.SerializeToString,
                response_deserializer=cluster_dot_v1_dot_cluster__service__pb2.ClusteringResult.FromString,
                _registered_method=True)
        self.ListClusteringResults = channel.unary_unary(
                '/photoops.cluster.v1.ClusterService/ListClusteringResults',
                request_serializer=cluster_dot_v1_dot_cluster__service__pb2.ListClusteringResultsRequest.SerializeToString,
                response_deserializer=cluster_dot_v1_dot_cluster__service__pb2.ListClusteringResultsResponse.FromString,
                _registered_method=True)


class ClusterServiceServicer:
    """Deterministic hierarchical clustering of a user's photos into an immutable
    tree. Clustering methods are pluggable behind a registry (SOLID): this slice
    ships `time_only`; space-time is a registered-later seam. Runs are async
    (result_id == async job id); see process.proto for the RabbitMQ contract.
    """

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListClusteringMethods(self, request, context):
        """The clustering methods this service can run (the registry surface).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateClusters(self, request, context):
        """Start an async clustering run over the caller's photos. Returns immediately
        with a PENDING result whose id equals the async job id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClusteringResult(self, request, context):
        """One clustering result as the full immutable tree, owner-scoped.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListClusteringResults(self, request, context):
        """The caller's clustering results (metadata only, no tree).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClusterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=common_dot_v1_dot_common__pb2.HealthCheckRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.HealthCheckResponse.SerializeToString,
            ),
            'ListClusteringMethods': grpc.unary_unary_rpc_method_handler(
                    servicer.ListClusteringMethods,
                    request_deserializer=cluster_dot_v1_dot_cluster__service__pb2.ListClusteringMethodsRequest.FromString,
                    response_serializer=cluster_dot_v1_dot_cluster__service__pb2.ListClusteringMethodsResponse.SerializeToString,
            ),
            'GenerateClusters': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateClusters,
                    request_deserializer=cluster_dot_v1_dot_cluster__service__pb2.GenerateClustersRequest.FromString,
                    response_serializer=cluster_dot_v1_dot_cluster__service__pb2.GenerateClustersResponse.SerializeToString,
            ),
            'GetClusteringResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusteringResult,
                    request_deserializer=cluster_dot_v1_dot_cluster__service__pb2.GetClusteringResultRequest.FromString,
                    response_serializer=cluster_dot_v1_dot_cluster__service__pb2.ClusteringResult.SerializeToString,
            ),
            'ListClusteringResults': grpc.unary_unary_rpc_method_handler(
                    servicer.ListClusteringResults,
                    request_deserializer=cluster_dot_v1_dot_cluster__service__pb2.ListClusteringResultsRequest.FromString,
                    response_serializer=cluster_dot_v1_dot_cluster__service__pb2.ListClusteringResultsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'photoops.cluster.v1.ClusterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('photoops.cluster.v1.ClusterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClusterService:
    """Deterministic hierarchical clustering of a user's photos into an immutable
    tree. Clustering methods are pluggable behind a registry (SOLID): this slice
    ships `time_only`; space-time is a registered-later seam. Runs are async
    (result_id == async job id); see process.proto for the RabbitMQ contract.
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photoops.cluster.v1.ClusterService/Health',
            common_dot_v1_dot_common__pb2.HealthCheckRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListClusteringMethods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photoops.cluster.v1.ClusterService/ListClusteringMethods',
            cluster_dot_v1_dot_cluster__service__pb2.ListClusteringMethodsRequest.SerializeToString,
            cluster_dot_v1_dot_cluster__service__pb2.ListClusteringMethodsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateClusters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photoops.cluster.v1.ClusterService/GenerateClusters',
            cluster_dot_v1_dot_cluster__service__pb2.GenerateClustersRequest.SerializeToString,
            cluster_dot_v1_dot_cluster__service__pb2.GenerateClustersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClusteringResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photoops.cluster.v1.ClusterService/GetClusteringResult',
            cluster_dot_v1_dot_cluster__service__pb2.GetClusteringResultRequest.SerializeToString,
            cluster_dot_v1_dot_cluster__service__pb2.ClusteringResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListClusteringResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photoops.cluster.v1.ClusterService/ListClusteringResults',
            cluster_dot_v1_dot_cluster__service__pb2.ListClusteringResultsRequest.SerializeToString,
            cluster_dot_v1_dot_cluster__service__pb2.ListClusteringResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
