# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cluster/v1/process.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'cluster/v1/process.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63luster/v1/process.proto\x12\x13photoops.cluster.v1\"\xa9\x01\n\x11\x43lusterProcessJob\x12\x1b\n\tresult_id\x18\x01 \x01(\tR\x08resultId\x12\x17\n\x07user_id\x18\x02 \x01(\tR\x06userId\x12\x16\n\x06method\x18\x03 \x01(\tR\x06method\x12\x1f\n\x0bparams_json\x18\x04 \x01(\tR\nparamsJson\x12%\n\x0e\x63orrelation_id\x18\x05 \x01(\tR\rcorrelationId\"\xd7\x01\n\x14\x43lusterProcessResult\x12\x1b\n\tresult_id\x18\x01 \x01(\tR\x08resultId\x12\x17\n\x07user_id\x18\x02 \x01(\tR\x06userId\x12%\n\x0e\x63orrelation_id\x18\x03 \x01(\tR\rcorrelationId\x12=\n\x07outcome\x18\x04 \x01(\x0e\x32#.photoops.cluster.v1.ClusterOutcomeR\x07outcome\x12#\n\rerror_message\x18\x05 \x01(\tR\x0c\x65rrorMessage*l\n\x0e\x43lusterOutcome\x12\x1f\n\x1b\x43LUSTER_OUTCOME_UNSPECIFIED\x10\x00\x12\x1d\n\x19\x43LUSTER_OUTCOME_SUCCEEDED\x10\x01\x12\x1a\n\x16\x43LUSTER_OUTCOME_FAILED\x10\x02\x42\x95\x01\n\x17\x63om.photoops.cluster.v1B\x0cProcessProtoP\x01\xa2\x02\x03PCX\xaa\x02\x13Photoops.Cluster.V1\xca\x02\x13Photoops\\Cluster\\V1\xe2\x02\x1fPhotoops\\Cluster\\V1\\GPBMetadata\xea\x02\x15Photoops::Cluster::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cluster.v1.process_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.photoops.cluster.v1B\014ProcessProtoP\001\242\002\003PCX\252\002\023Photoops.Cluster.V1\312\002\023Photoops\\Cluster\\V1\342\002\037Photoops\\Cluster\\V1\\GPBMetadata\352\002\025Photoops::Cluster::V1'
  _globals['_CLUSTEROUTCOME']._serialized_start=439
  _globals['_CLUSTEROUTCOME']._serialized_end=547
  _globals['_CLUSTERPROCESSJOB']._serialized_start=50
  _globals['_CLUSTERPROCESSJOB']._serialized_end=219
  _globals['_CLUSTERPROCESSRESULT']._serialized_start=222
  _globals['_CLUSTERPROCESSRESULT']._serialized_end=437
# @@protoc_insertion_point(module_scope)
