// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: usage/v1/consumption.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "photoops.usage.v1";

/**
 * One raw measurement within an operation. An operation may consume several
 * resources at once (e.g. storage bytes + a processing count) → several
 * Measurements under a single event/idempotency_key.
 */
export interface Measurement {
  /** photo_original_stored | photo_variant_generated | photo_processed | cluster_generated | ... */
  eventType: string;
  /** storage | processing | ... */
  resourceType: string;
  /** raw amount expressed in `unit` */
  quantity: string;
  /** byte | operation | byte_second | cpu_second | ... */
  unit: string;
  /** photo | photo_variant | processing_job | cluster_result | ... */
  sourceEntityType: string;
  /** typed UUID; may reference another service's entity (no cross-service FK) */
  sourceEntityId: string;
}

/**
 * Published by an operation's runtime when the operation completes; consumed by
 * usage-service. The whole event is all-or-nothing under `idempotency_key`.
 */
export interface ConsumptionEvent {
  /** charge-once key (media job_id, "original:{photo_id}", cluster result_id) */
  idempotencyKey: string;
  /** UUID v7; no cross-service FK */
  userId: string;
  /** physical provenance: where this run executed (instance env), e.g. "local-demo" */
  provider: string;
  /** ISO-8601 instant the operation completed (pricing-resolution epoch) */
  occurredAt: string;
  measurements: Measurement[];
  /** W3C traceparent for log/trace threading; NOT an idempotency key */
  correlationId: string;
}

export const PHOTOOPS_USAGE_V1_PACKAGE_NAME = "photoops.usage.v1";

function createBaseMeasurement(): Measurement {
  return { eventType: "", resourceType: "", quantity: "0", unit: "", sourceEntityType: "", sourceEntityId: "" };
}

export const Measurement: MessageFns<Measurement> = {
  encode(message: Measurement, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventType !== "") {
      writer.uint32(10).string(message.eventType);
    }
    if (message.resourceType !== "") {
      writer.uint32(18).string(message.resourceType);
    }
    if (message.quantity !== "0") {
      writer.uint32(24).int64(message.quantity);
    }
    if (message.unit !== "") {
      writer.uint32(34).string(message.unit);
    }
    if (message.sourceEntityType !== "") {
      writer.uint32(42).string(message.sourceEntityType);
    }
    if (message.sourceEntityId !== "") {
      writer.uint32(50).string(message.sourceEntityId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Measurement {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMeasurement();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.eventType = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.resourceType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.quantity = reader.int64().toString();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.unit = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.sourceEntityType = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.sourceEntityId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseConsumptionEvent(): ConsumptionEvent {
  return { idempotencyKey: "", userId: "", provider: "", occurredAt: "", measurements: [], correlationId: "" };
}

export const ConsumptionEvent: MessageFns<ConsumptionEvent> = {
  encode(message: ConsumptionEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.idempotencyKey !== "") {
      writer.uint32(10).string(message.idempotencyKey);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.provider !== "") {
      writer.uint32(26).string(message.provider);
    }
    if (message.occurredAt !== "") {
      writer.uint32(34).string(message.occurredAt);
    }
    for (const v of message.measurements) {
      Measurement.encode(v!, writer.uint32(42).fork()).join();
    }
    if (message.correlationId !== "") {
      writer.uint32(50).string(message.correlationId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConsumptionEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConsumptionEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.idempotencyKey = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.provider = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.occurredAt = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.measurements.push(Measurement.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.correlationId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
