// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: usage/v1/usage_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { HealthCheckRequest, HealthCheckResponse } from "../../common/v1/common";

export const protobufPackage = "photoops.usage.v1";

export interface GetUsageSummaryRequest {
}

export interface GetUsageSummaryResponse {
  estimatedMonthlyCost: string;
}

export const PHOTOOPS_USAGE_V1_PACKAGE_NAME = "photoops.usage.v1";

function createBaseGetUsageSummaryRequest(): GetUsageSummaryRequest {
  return {};
}

export const GetUsageSummaryRequest: MessageFns<GetUsageSummaryRequest> = {
  encode(_: GetUsageSummaryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUsageSummaryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUsageSummaryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUsageSummaryResponse(): GetUsageSummaryResponse {
  return { estimatedMonthlyCost: "" };
}

export const GetUsageSummaryResponse: MessageFns<GetUsageSummaryResponse> = {
  encode(message: GetUsageSummaryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.estimatedMonthlyCost !== "") {
      writer.uint32(10).string(message.estimatedMonthlyCost);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUsageSummaryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUsageSummaryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.estimatedMonthlyCost = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface UsageServiceClient {
  health(request: HealthCheckRequest): Observable<HealthCheckResponse>;

  getUsageSummary(request: GetUsageSummaryRequest): Observable<GetUsageSummaryResponse>;
}

export interface UsageServiceController {
  health(
    request: HealthCheckRequest,
  ): Promise<HealthCheckResponse> | Observable<HealthCheckResponse> | HealthCheckResponse;

  getUsageSummary(
    request: GetUsageSummaryRequest,
  ): Promise<GetUsageSummaryResponse> | Observable<GetUsageSummaryResponse> | GetUsageSummaryResponse;
}

export function UsageServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["health", "getUsageSummary"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UsageService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UsageService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USAGE_SERVICE_NAME = "UsageService";

export type UsageServiceService = typeof UsageServiceService;
export const UsageServiceService = {
  health: {
    path: "/photoops.usage.v1.UsageService/Health" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HealthCheckRequest): Buffer => Buffer.from(HealthCheckRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HealthCheckRequest => HealthCheckRequest.decode(value),
    responseSerialize: (value: HealthCheckResponse): Buffer => Buffer.from(HealthCheckResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HealthCheckResponse => HealthCheckResponse.decode(value),
  },
  getUsageSummary: {
    path: "/photoops.usage.v1.UsageService/GetUsageSummary" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetUsageSummaryRequest): Buffer =>
      Buffer.from(GetUsageSummaryRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUsageSummaryRequest => GetUsageSummaryRequest.decode(value),
    responseSerialize: (value: GetUsageSummaryResponse): Buffer =>
      Buffer.from(GetUsageSummaryResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetUsageSummaryResponse => GetUsageSummaryResponse.decode(value),
  },
} as const;

export interface UsageServiceServer extends UntypedServiceImplementation {
  health: handleUnaryCall<HealthCheckRequest, HealthCheckResponse>;
  getUsageSummary: handleUnaryCall<GetUsageSummaryRequest, GetUsageSummaryResponse>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
