// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: usage/v1/usage_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { HealthCheckRequest, HealthCheckResponse } from "../../common/v1/common";

export const protobufPackage = "photoops.usage.v1";

export interface GetUsageSummaryRequest {
  /** caller-supplied from the validated session in api-gateway */
  userId: string;
}

/**
 * Per-user usage rollup: raw per-resource lines + an estimated monthly cost.
 * Lines are general (event_type/resource_type) so new producers (clusters in
 * s013, posts later) surface automatically without a schema change.
 */
export interface GetUsageSummaryResponse {
  lines: UsageLine[];
  /** decimal string, e.g. "0.37"; resolved from the pricing layer */
  estimatedMonthlyCost: string;
  /** e.g. "USD" */
  currency: string;
}

export interface UsageLine {
  eventType: string;
  resourceType: string;
  totalQuantity: string;
  unit: string;
}

export const PHOTOOPS_USAGE_V1_PACKAGE_NAME = "photoops.usage.v1";

function createBaseGetUsageSummaryRequest(): GetUsageSummaryRequest {
  return { userId: "" };
}

export const GetUsageSummaryRequest: MessageFns<GetUsageSummaryRequest> = {
  encode(message: GetUsageSummaryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUsageSummaryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUsageSummaryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUsageSummaryResponse(): GetUsageSummaryResponse {
  return { lines: [], estimatedMonthlyCost: "", currency: "" };
}

export const GetUsageSummaryResponse: MessageFns<GetUsageSummaryResponse> = {
  encode(message: GetUsageSummaryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.lines) {
      UsageLine.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.estimatedMonthlyCost !== "") {
      writer.uint32(18).string(message.estimatedMonthlyCost);
    }
    if (message.currency !== "") {
      writer.uint32(26).string(message.currency);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUsageSummaryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUsageSummaryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.lines.push(UsageLine.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.estimatedMonthlyCost = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUsageLine(): UsageLine {
  return { eventType: "", resourceType: "", totalQuantity: "0", unit: "" };
}

export const UsageLine: MessageFns<UsageLine> = {
  encode(message: UsageLine, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventType !== "") {
      writer.uint32(10).string(message.eventType);
    }
    if (message.resourceType !== "") {
      writer.uint32(18).string(message.resourceType);
    }
    if (message.totalQuantity !== "0") {
      writer.uint32(24).int64(message.totalQuantity);
    }
    if (message.unit !== "") {
      writer.uint32(34).string(message.unit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UsageLine {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUsageLine();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.eventType = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.resourceType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalQuantity = reader.int64().toString();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.unit = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface UsageServiceClient {
  health(request: HealthCheckRequest): Observable<HealthCheckResponse>;

  getUsageSummary(request: GetUsageSummaryRequest): Observable<GetUsageSummaryResponse>;
}

export interface UsageServiceController {
  health(
    request: HealthCheckRequest,
  ): Promise<HealthCheckResponse> | Observable<HealthCheckResponse> | HealthCheckResponse;

  getUsageSummary(
    request: GetUsageSummaryRequest,
  ): Promise<GetUsageSummaryResponse> | Observable<GetUsageSummaryResponse> | GetUsageSummaryResponse;
}

export function UsageServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["health", "getUsageSummary"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UsageService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UsageService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USAGE_SERVICE_NAME = "UsageService";

export type UsageServiceService = typeof UsageServiceService;
export const UsageServiceService = {
  health: {
    path: "/photoops.usage.v1.UsageService/Health" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HealthCheckRequest): Buffer => Buffer.from(HealthCheckRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HealthCheckRequest => HealthCheckRequest.decode(value),
    responseSerialize: (value: HealthCheckResponse): Buffer => Buffer.from(HealthCheckResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HealthCheckResponse => HealthCheckResponse.decode(value),
  },
  getUsageSummary: {
    path: "/photoops.usage.v1.UsageService/GetUsageSummary" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetUsageSummaryRequest): Buffer =>
      Buffer.from(GetUsageSummaryRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUsageSummaryRequest => GetUsageSummaryRequest.decode(value),
    responseSerialize: (value: GetUsageSummaryResponse): Buffer =>
      Buffer.from(GetUsageSummaryResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetUsageSummaryResponse => GetUsageSummaryResponse.decode(value),
  },
} as const;

export interface UsageServiceServer extends UntypedServiceImplementation {
  health: handleUnaryCall<HealthCheckRequest, HealthCheckResponse>;
  getUsageSummary: handleUnaryCall<GetUsageSummaryRequest, GetUsageSummaryResponse>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
