// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: connector/v1/connector_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { HealthCheckRequest, HealthCheckResponse } from "../../common/v1/common";

export const protobufPackage = "photoops.connector.v1";

export interface CreateShareTextRequest {
  postId: string;
}

export interface CreateShareTextResponse {
  text: string;
}

export const PHOTOOPS_CONNECTOR_V1_PACKAGE_NAME = "photoops.connector.v1";

function createBaseCreateShareTextRequest(): CreateShareTextRequest {
  return { postId: "" };
}

export const CreateShareTextRequest: MessageFns<CreateShareTextRequest> = {
  encode(message: CreateShareTextRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.postId !== "") {
      writer.uint32(10).string(message.postId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateShareTextRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateShareTextRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.postId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCreateShareTextResponse(): CreateShareTextResponse {
  return { text: "" };
}

export const CreateShareTextResponse: MessageFns<CreateShareTextResponse> = {
  encode(message: CreateShareTextResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateShareTextResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateShareTextResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface ConnectorServiceClient {
  health(request: HealthCheckRequest): Observable<HealthCheckResponse>;

  createShareText(request: CreateShareTextRequest): Observable<CreateShareTextResponse>;
}

export interface ConnectorServiceController {
  health(
    request: HealthCheckRequest,
  ): Promise<HealthCheckResponse> | Observable<HealthCheckResponse> | HealthCheckResponse;

  createShareText(
    request: CreateShareTextRequest,
  ): Promise<CreateShareTextResponse> | Observable<CreateShareTextResponse> | CreateShareTextResponse;
}

export function ConnectorServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["health", "createShareText"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ConnectorService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ConnectorService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CONNECTOR_SERVICE_NAME = "ConnectorService";

export type ConnectorServiceService = typeof ConnectorServiceService;
export const ConnectorServiceService = {
  health: {
    path: "/photoops.connector.v1.ConnectorService/Health" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HealthCheckRequest): Buffer => Buffer.from(HealthCheckRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HealthCheckRequest => HealthCheckRequest.decode(value),
    responseSerialize: (value: HealthCheckResponse): Buffer => Buffer.from(HealthCheckResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HealthCheckResponse => HealthCheckResponse.decode(value),
  },
  createShareText: {
    path: "/photoops.connector.v1.ConnectorService/CreateShareText" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateShareTextRequest): Buffer =>
      Buffer.from(CreateShareTextRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateShareTextRequest => CreateShareTextRequest.decode(value),
    responseSerialize: (value: CreateShareTextResponse): Buffer =>
      Buffer.from(CreateShareTextResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateShareTextResponse => CreateShareTextResponse.decode(value),
  },
} as const;

export interface ConnectorServiceServer extends UntypedServiceImplementation {
  health: handleUnaryCall<HealthCheckRequest, HealthCheckResponse>;
  createShareText: handleUnaryCall<CreateShareTextRequest, CreateShareTextResponse>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
