# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/v1/common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'common/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ommon/v1/common.proto\x12\x12photoops.common.v1\"\x07\n\x05\x45mpty\"\x14\n\x12HealthCheckRequest\"G\n\x13HealthCheckResponse\x12\x16\n\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n\x07service\x18\x02 \x01(\tR\x07service\"d\n\rErrorResponse\x12\x12\n\x04\x63ode\x18\x01 \x01(\tR\x04\x63ode\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message\x12%\n\x0e\x63orrelation_id\x18\x03 \x01(\tR\rcorrelationIdB\x8f\x01\n\x16\x63om.photoops.common.v1B\x0b\x43ommonProtoP\x01\xa2\x02\x03PCX\xaa\x02\x12Photoops.Common.V1\xca\x02\x12Photoops\\Common\\V1\xe2\x02\x1ePhotoops\\Common\\V1\\GPBMetadata\xea\x02\x14Photoops::Common::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.photoops.common.v1B\013CommonProtoP\001\242\002\003PCX\252\002\022Photoops.Common.V1\312\002\022Photoops\\Common\\V1\342\002\036Photoops\\Common\\V1\\GPBMetadata\352\002\024Photoops::Common::V1'
  _globals['_EMPTY']._serialized_start=46
  _globals['_EMPTY']._serialized_end=53
  _globals['_HEALTHCHECKREQUEST']._serialized_start=55
  _globals['_HEALTHCHECKREQUEST']._serialized_end=75
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=77
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=148
  _globals['_ERRORRESPONSE']._serialized_start=150
  _globals['_ERRORRESPONSE']._serialized_end=250
# @@protoc_insertion_point(module_scope)
