// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: publication/v1/publication_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { HealthCheckRequest, HealthCheckResponse } from "../../common/v1/common";

export const protobufPackage = "photoops.publication.v1";

export interface CreateDraftFromClusterRequest {
  clusterId: string;
}

export interface CreateDraftFromClusterResponse {
  postId: string;
}

export const PHOTOOPS_PUBLICATION_V1_PACKAGE_NAME = "photoops.publication.v1";

function createBaseCreateDraftFromClusterRequest(): CreateDraftFromClusterRequest {
  return { clusterId: "" };
}

export const CreateDraftFromClusterRequest: MessageFns<CreateDraftFromClusterRequest> = {
  encode(message: CreateDraftFromClusterRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clusterId !== "") {
      writer.uint32(10).string(message.clusterId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateDraftFromClusterRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateDraftFromClusterRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clusterId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCreateDraftFromClusterResponse(): CreateDraftFromClusterResponse {
  return { postId: "" };
}

export const CreateDraftFromClusterResponse: MessageFns<CreateDraftFromClusterResponse> = {
  encode(message: CreateDraftFromClusterResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.postId !== "") {
      writer.uint32(10).string(message.postId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateDraftFromClusterResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateDraftFromClusterResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.postId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface PublicationServiceClient {
  health(request: HealthCheckRequest): Observable<HealthCheckResponse>;

  createDraftFromCluster(request: CreateDraftFromClusterRequest): Observable<CreateDraftFromClusterResponse>;
}

export interface PublicationServiceController {
  health(
    request: HealthCheckRequest,
  ): Promise<HealthCheckResponse> | Observable<HealthCheckResponse> | HealthCheckResponse;

  createDraftFromCluster(
    request: CreateDraftFromClusterRequest,
  ):
    | Promise<CreateDraftFromClusterResponse>
    | Observable<CreateDraftFromClusterResponse>
    | CreateDraftFromClusterResponse;
}

export function PublicationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["health", "createDraftFromCluster"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PublicationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PublicationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PUBLICATION_SERVICE_NAME = "PublicationService";

export type PublicationServiceService = typeof PublicationServiceService;
export const PublicationServiceService = {
  health: {
    path: "/photoops.publication.v1.PublicationService/Health" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HealthCheckRequest): Buffer => Buffer.from(HealthCheckRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HealthCheckRequest => HealthCheckRequest.decode(value),
    responseSerialize: (value: HealthCheckResponse): Buffer => Buffer.from(HealthCheckResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HealthCheckResponse => HealthCheckResponse.decode(value),
  },
  createDraftFromCluster: {
    path: "/photoops.publication.v1.PublicationService/CreateDraftFromCluster" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateDraftFromClusterRequest): Buffer =>
      Buffer.from(CreateDraftFromClusterRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateDraftFromClusterRequest => CreateDraftFromClusterRequest.decode(value),
    responseSerialize: (value: CreateDraftFromClusterResponse): Buffer =>
      Buffer.from(CreateDraftFromClusterResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateDraftFromClusterResponse =>
      CreateDraftFromClusterResponse.decode(value),
  },
} as const;

export interface PublicationServiceServer extends UntypedServiceImplementation {
  health: handleUnaryCall<HealthCheckRequest, HealthCheckResponse>;
  createDraftFromCluster: handleUnaryCall<CreateDraftFromClusterRequest, CreateDraftFromClusterResponse>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
