// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: usage/v1/consumption.proto

package usagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One raw measurement within an operation. An operation may consume several
// resources at once (e.g. storage bytes + a processing count) → several
// Measurements under a single event/idempotency_key.
type Measurement struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventType        string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`                        // photo_original_stored | photo_variant_generated | photo_processed | cluster_generated | ...
	ResourceType     string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`               // storage | processing | ...
	Quantity         int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`                                          // raw amount expressed in `unit`
	Unit             string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`                                                   // byte | operation | byte_second | cpu_second | ...
	SourceEntityType string                 `protobuf:"bytes,5,opt,name=source_entity_type,json=sourceEntityType,proto3" json:"source_entity_type,omitempty"` // photo | photo_variant | processing_job | cluster_result | ...
	SourceEntityId   string                 `protobuf:"bytes,6,opt,name=source_entity_id,json=sourceEntityId,proto3" json:"source_entity_id,omitempty"`       // typed UUID; may reference another service's entity (no cross-service FK)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Measurement) Reset() {
	*x = Measurement{}
	mi := &file_usage_v1_consumption_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Measurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Measurement) ProtoMessage() {}

func (x *Measurement) ProtoReflect() protoreflect.Message {
	mi := &file_usage_v1_consumption_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Measurement.ProtoReflect.Descriptor instead.
func (*Measurement) Descriptor() ([]byte, []int) {
	return file_usage_v1_consumption_proto_rawDescGZIP(), []int{0}
}

func (x *Measurement) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Measurement) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *Measurement) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Measurement) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Measurement) GetSourceEntityType() string {
	if x != nil {
		return x.SourceEntityType
	}
	return ""
}

func (x *Measurement) GetSourceEntityId() string {
	if x != nil {
		return x.SourceEntityId
	}
	return ""
}

// Published by an operation's runtime when the operation completes; consumed by
// usage-service. The whole event is all-or-nothing under `idempotency_key`.
type ConsumptionEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // charge-once key (media job_id, "original:{photo_id}", cluster result_id)
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // UUID v7; no cross-service FK
	Provider       string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`                                   // physical provenance: where this run executed (instance env), e.g. "local-demo"
	OccurredAt     string                 `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`             // ISO-8601 instant the operation completed (pricing-resolution epoch)
	Measurements   []*Measurement         `protobuf:"bytes,5,rep,name=measurements,proto3" json:"measurements,omitempty"`
	CorrelationId  string                 `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // W3C traceparent for log/trace threading; NOT an idempotency key
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConsumptionEvent) Reset() {
	*x = ConsumptionEvent{}
	mi := &file_usage_v1_consumption_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumptionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumptionEvent) ProtoMessage() {}

func (x *ConsumptionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_usage_v1_consumption_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumptionEvent.ProtoReflect.Descriptor instead.
func (*ConsumptionEvent) Descriptor() ([]byte, []int) {
	return file_usage_v1_consumption_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumptionEvent) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ConsumptionEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConsumptionEvent) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ConsumptionEvent) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *ConsumptionEvent) GetMeasurements() []*Measurement {
	if x != nil {
		return x.Measurements
	}
	return nil
}

func (x *ConsumptionEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

var File_usage_v1_consumption_proto protoreflect.FileDescriptor

const file_usage_v1_consumption_proto_rawDesc = "" +
	"\n" +
	"\x1ausage/v1/consumption.proto\x12\x11photoops.usage.v1\"\xd9\x01\n" +
	"\vMeasurement\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x12,\n" +
	"\x12source_entity_type\x18\x05 \x01(\tR\x10sourceEntityType\x12(\n" +
	"\x10source_entity_id\x18\x06 \x01(\tR\x0esourceEntityId\"\xfc\x01\n" +
	"\x10ConsumptionEvent\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x1f\n" +
	"\voccurred_at\x18\x04 \x01(\tR\n" +
	"occurredAt\x12B\n" +
	"\fmeasurements\x18\x05 \x03(\v2\x1e.photoops.usage.v1.MeasurementR\fmeasurements\x12%\n" +
	"\x0ecorrelation_id\x18\x06 \x01(\tR\rcorrelationIdB\xcf\x01\n" +
	"\x15com.photoops.usage.v1B\x10ConsumptionProtoP\x01Z>github.com/photoops/usage-service/internal/pb/usage/v1;usagev1\xa2\x02\x03PUX\xaa\x02\x11Photoops.Usage.V1\xca\x02\x11Photoops\\Usage\\V1\xe2\x02\x1dPhotoops\\Usage\\V1\\GPBMetadata\xea\x02\x13Photoops::Usage::V1b\x06proto3"

var (
	file_usage_v1_consumption_proto_rawDescOnce sync.Once
	file_usage_v1_consumption_proto_rawDescData []byte
)

func file_usage_v1_consumption_proto_rawDescGZIP() []byte {
	file_usage_v1_consumption_proto_rawDescOnce.Do(func() {
		file_usage_v1_consumption_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_usage_v1_consumption_proto_rawDesc), len(file_usage_v1_consumption_proto_rawDesc)))
	})
	return file_usage_v1_consumption_proto_rawDescData
}

var file_usage_v1_consumption_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_usage_v1_consumption_proto_goTypes = []any{
	(*Measurement)(nil),      // 0: photoops.usage.v1.Measurement
	(*ConsumptionEvent)(nil), // 1: photoops.usage.v1.ConsumptionEvent
}
var file_usage_v1_consumption_proto_depIdxs = []int32{
	0, // 0: photoops.usage.v1.ConsumptionEvent.measurements:type_name -> photoops.usage.v1.Measurement
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_usage_v1_consumption_proto_init() }
func file_usage_v1_consumption_proto_init() {
	if File_usage_v1_consumption_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_usage_v1_consumption_proto_rawDesc), len(file_usage_v1_consumption_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_usage_v1_consumption_proto_goTypes,
		DependencyIndexes: file_usage_v1_consumption_proto_depIdxs,
		MessageInfos:      file_usage_v1_consumption_proto_msgTypes,
	}.Build()
	File_usage_v1_consumption_proto = out.File
	file_usage_v1_consumption_proto_goTypes = nil
	file_usage_v1_consumption_proto_depIdxs = nil
}
