// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: usage/v1/usage_service.proto

package usagev1

import (
	v1 "github.com/photoops/usage-service/internal/pb/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUsageSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // caller-supplied from the validated session in api-gateway
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageSummaryRequest) Reset() {
	*x = GetUsageSummaryRequest{}
	mi := &file_usage_v1_usage_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageSummaryRequest) ProtoMessage() {}

func (x *GetUsageSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usage_v1_usage_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetUsageSummaryRequest) Descriptor() ([]byte, []int) {
	return file_usage_v1_usage_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetUsageSummaryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Per-user usage rollup: raw per-resource lines + an estimated monthly cost.
// Lines are general (event_type/resource_type) so new producers (clusters in
// s013, posts later) surface automatically without a schema change.
type GetUsageSummaryResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Lines                []*UsageLine           `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	EstimatedMonthlyCost string                 `protobuf:"bytes,2,opt,name=estimated_monthly_cost,json=estimatedMonthlyCost,proto3" json:"estimated_monthly_cost,omitempty"` // decimal string, e.g. "0.37"; resolved from the pricing layer
	Currency             string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`                                                       // e.g. "USD"
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetUsageSummaryResponse) Reset() {
	*x = GetUsageSummaryResponse{}
	mi := &file_usage_v1_usage_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageSummaryResponse) ProtoMessage() {}

func (x *GetUsageSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usage_v1_usage_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetUsageSummaryResponse) Descriptor() ([]byte, []int) {
	return file_usage_v1_usage_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetUsageSummaryResponse) GetLines() []*UsageLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *GetUsageSummaryResponse) GetEstimatedMonthlyCost() string {
	if x != nil {
		return x.EstimatedMonthlyCost
	}
	return ""
}

func (x *GetUsageSummaryResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type UsageLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	TotalQuantity int64                  `protobuf:"varint,3,opt,name=total_quantity,json=totalQuantity,proto3" json:"total_quantity,omitempty"`
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageLine) Reset() {
	*x = UsageLine{}
	mi := &file_usage_v1_usage_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageLine) ProtoMessage() {}

func (x *UsageLine) ProtoReflect() protoreflect.Message {
	mi := &file_usage_v1_usage_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageLine.ProtoReflect.Descriptor instead.
func (*UsageLine) Descriptor() ([]byte, []int) {
	return file_usage_v1_usage_service_proto_rawDescGZIP(), []int{2}
}

func (x *UsageLine) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *UsageLine) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *UsageLine) GetTotalQuantity() int64 {
	if x != nil {
		return x.TotalQuantity
	}
	return 0
}

func (x *UsageLine) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

var File_usage_v1_usage_service_proto protoreflect.FileDescriptor

const file_usage_v1_usage_service_proto_rawDesc = "" +
	"\n" +
	"\x1cusage/v1/usage_service.proto\x12\x11photoops.usage.v1\x1a\x16common/v1/common.proto\x1a\x1cgoogle/api/annotations.proto\"1\n" +
	"\x16GetUsageSummaryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x9f\x01\n" +
	"\x17GetUsageSummaryResponse\x122\n" +
	"\x05lines\x18\x01 \x03(\v2\x1c.photoops.usage.v1.UsageLineR\x05lines\x124\n" +
	"\x16estimated_monthly_cost\x18\x02 \x01(\tR\x14estimatedMonthlyCost\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"\x8a\x01\n" +
	"\tUsageLine\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12%\n" +
	"\x0etotal_quantity\x18\x03 \x01(\x03R\rtotalQuantity\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit2\x89\x02\n" +
	"\fUsageService\x12s\n" +
	"\x06Health\x12&.photoops.common.v1.HealthCheckRequest\x1a'.photoops.common.v1.HealthCheckResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/usage/health\x12\x83\x01\n" +
	"\x0fGetUsageSummary\x12).photoops.usage.v1.GetUsageSummaryRequest\x1a*.photoops.usage.v1.GetUsageSummaryResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/usage/summaryB\xd0\x01\n" +
	"\x15com.photoops.usage.v1B\x11UsageServiceProtoP\x01Z>github.com/photoops/usage-service/internal/pb/usage/v1;usagev1\xa2\x02\x03PUX\xaa\x02\x11Photoops.Usage.V1\xca\x02\x11Photoops\\Usage\\V1\xe2\x02\x1dPhotoops\\Usage\\V1\\GPBMetadata\xea\x02\x13Photoops::Usage::V1b\x06proto3"

var (
	file_usage_v1_usage_service_proto_rawDescOnce sync.Once
	file_usage_v1_usage_service_proto_rawDescData []byte
)

func file_usage_v1_usage_service_proto_rawDescGZIP() []byte {
	file_usage_v1_usage_service_proto_rawDescOnce.Do(func() {
		file_usage_v1_usage_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_usage_v1_usage_service_proto_rawDesc), len(file_usage_v1_usage_service_proto_rawDesc)))
	})
	return file_usage_v1_usage_service_proto_rawDescData
}

var file_usage_v1_usage_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_usage_v1_usage_service_proto_goTypes = []any{
	(*GetUsageSummaryRequest)(nil),  // 0: photoops.usage.v1.GetUsageSummaryRequest
	(*GetUsageSummaryResponse)(nil), // 1: photoops.usage.v1.GetUsageSummaryResponse
	(*UsageLine)(nil),               // 2: photoops.usage.v1.UsageLine
	(*v1.HealthCheckRequest)(nil),   // 3: photoops.common.v1.HealthCheckRequest
	(*v1.HealthCheckResponse)(nil),  // 4: photoops.common.v1.HealthCheckResponse
}
var file_usage_v1_usage_service_proto_depIdxs = []int32{
	2, // 0: photoops.usage.v1.GetUsageSummaryResponse.lines:type_name -> photoops.usage.v1.UsageLine
	3, // 1: photoops.usage.v1.UsageService.Health:input_type -> photoops.common.v1.HealthCheckRequest
	0, // 2: photoops.usage.v1.UsageService.GetUsageSummary:input_type -> photoops.usage.v1.GetUsageSummaryRequest
	4, // 3: photoops.usage.v1.UsageService.Health:output_type -> photoops.common.v1.HealthCheckResponse
	1, // 4: photoops.usage.v1.UsageService.GetUsageSummary:output_type -> photoops.usage.v1.GetUsageSummaryResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_usage_v1_usage_service_proto_init() }
func file_usage_v1_usage_service_proto_init() {
	if File_usage_v1_usage_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_usage_v1_usage_service_proto_rawDesc), len(file_usage_v1_usage_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_usage_v1_usage_service_proto_goTypes,
		DependencyIndexes: file_usage_v1_usage_service_proto_depIdxs,
		MessageInfos:      file_usage_v1_usage_service_proto_msgTypes,
	}.Build()
	File_usage_v1_usage_service_proto = out.File
	file_usage_v1_usage_service_proto_goTypes = nil
	file_usage_v1_usage_service_proto_depIdxs = nil
}
