// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: cluster/v1/cluster_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { HealthCheckRequest, HealthCheckResponse } from "../../common/v1/common";

export const protobufPackage = "photoops.cluster.v1";

export interface GenerateClustersRequest {
  scope: string;
}

export interface GenerateClustersResponse {
  jobId: string;
}

export const PHOTOOPS_CLUSTER_V1_PACKAGE_NAME = "photoops.cluster.v1";

function createBaseGenerateClustersRequest(): GenerateClustersRequest {
  return { scope: "" };
}

export const GenerateClustersRequest: MessageFns<GenerateClustersRequest> = {
  encode(message: GenerateClustersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.scope !== "") {
      writer.uint32(10).string(message.scope);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenerateClustersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenerateClustersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.scope = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGenerateClustersResponse(): GenerateClustersResponse {
  return { jobId: "" };
}

export const GenerateClustersResponse: MessageFns<GenerateClustersResponse> = {
  encode(message: GenerateClustersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenerateClustersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenerateClustersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface ClusterServiceClient {
  health(request: HealthCheckRequest): Observable<HealthCheckResponse>;

  generateClusters(request: GenerateClustersRequest): Observable<GenerateClustersResponse>;
}

export interface ClusterServiceController {
  health(
    request: HealthCheckRequest,
  ): Promise<HealthCheckResponse> | Observable<HealthCheckResponse> | HealthCheckResponse;

  generateClusters(
    request: GenerateClustersRequest,
  ): Promise<GenerateClustersResponse> | Observable<GenerateClustersResponse> | GenerateClustersResponse;
}

export function ClusterServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["health", "generateClusters"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ClusterService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ClusterService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CLUSTER_SERVICE_NAME = "ClusterService";

export type ClusterServiceService = typeof ClusterServiceService;
export const ClusterServiceService = {
  health: {
    path: "/photoops.cluster.v1.ClusterService/Health" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HealthCheckRequest): Buffer => Buffer.from(HealthCheckRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HealthCheckRequest => HealthCheckRequest.decode(value),
    responseSerialize: (value: HealthCheckResponse): Buffer => Buffer.from(HealthCheckResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HealthCheckResponse => HealthCheckResponse.decode(value),
  },
  generateClusters: {
    path: "/photoops.cluster.v1.ClusterService/GenerateClusters" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GenerateClustersRequest): Buffer =>
      Buffer.from(GenerateClustersRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GenerateClustersRequest => GenerateClustersRequest.decode(value),
    responseSerialize: (value: GenerateClustersResponse): Buffer =>
      Buffer.from(GenerateClustersResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GenerateClustersResponse => GenerateClustersResponse.decode(value),
  },
} as const;

export interface ClusterServiceServer extends UntypedServiceImplementation {
  health: handleUnaryCall<HealthCheckRequest, HealthCheckResponse>;
  generateClusters: handleUnaryCall<GenerateClustersRequest, GenerateClustersResponse>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
