// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: cluster/v1/process.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "photoops.cluster.v1";

/** Terminal outcome of a clustering run. */
export enum ClusterOutcome {
  CLUSTER_OUTCOME_UNSPECIFIED = 0,
  CLUSTER_OUTCOME_SUCCEEDED = 1,
  CLUSTER_OUTCOME_FAILED = 2,
  UNRECOGNIZED = -1,
}

/**
 * Job published by cluster-service (API role) when a run is accepted; consumed
 * by cluster-worker. The tree is computed + persisted by the worker; only the
 * terminal status flip travels back on the result (the tree stays in cluster-db).
 */
export interface ClusterProcessJob {
  /** UUID v7, == ClusteringResult.id (idempotency key) */
  resultId: string;
  userId: string;
  /** method id from the registry */
  method: string;
  /** resolved params JSON ("" -> method defaults) */
  paramsJson: string;
  /** threaded through logs/trace; not an idempotency key */
  correlationId: string;
}

/**
 * Result published by cluster-worker; consumed by cluster-service to flip the
 * persisted result row to READY / FAILED.
 */
export interface ClusterProcessResult {
  resultId: string;
  userId: string;
  correlationId: string;
  outcome: ClusterOutcome;
  /** when FAILED */
  errorMessage: string;
}

export const PHOTOOPS_CLUSTER_V1_PACKAGE_NAME = "photoops.cluster.v1";

function createBaseClusterProcessJob(): ClusterProcessJob {
  return { resultId: "", userId: "", method: "", paramsJson: "", correlationId: "" };
}

export const ClusterProcessJob: MessageFns<ClusterProcessJob> = {
  encode(message: ClusterProcessJob, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.resultId !== "") {
      writer.uint32(10).string(message.resultId);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.method !== "") {
      writer.uint32(26).string(message.method);
    }
    if (message.paramsJson !== "") {
      writer.uint32(34).string(message.paramsJson);
    }
    if (message.correlationId !== "") {
      writer.uint32(42).string(message.correlationId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClusterProcessJob {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClusterProcessJob();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.resultId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.method = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.paramsJson = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.correlationId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseClusterProcessResult(): ClusterProcessResult {
  return { resultId: "", userId: "", correlationId: "", outcome: 0, errorMessage: "" };
}

export const ClusterProcessResult: MessageFns<ClusterProcessResult> = {
  encode(message: ClusterProcessResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.resultId !== "") {
      writer.uint32(10).string(message.resultId);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.correlationId !== "") {
      writer.uint32(26).string(message.correlationId);
    }
    if (message.outcome !== 0) {
      writer.uint32(32).int32(message.outcome);
    }
    if (message.errorMessage !== "") {
      writer.uint32(42).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClusterProcessResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClusterProcessResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.resultId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.correlationId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.outcome = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
