# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: usage/v1/consumption.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'usage/v1/consumption.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ausage/v1/consumption.proto\x12\x11photoops.usage.v1\"\xd9\x01\n\x0bMeasurement\x12\x1d\n\nevent_type\x18\x01 \x01(\tR\teventType\x12#\n\rresource_type\x18\x02 \x01(\tR\x0cresourceType\x12\x1a\n\x08quantity\x18\x03 \x01(\x03R\x08quantity\x12\x12\n\x04unit\x18\x04 \x01(\tR\x04unit\x12,\n\x12source_entity_type\x18\x05 \x01(\tR\x10sourceEntityType\x12(\n\x10source_entity_id\x18\x06 \x01(\tR\x0esourceEntityId\"\xfc\x01\n\x10\x43onsumptionEvent\x12\'\n\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x17\n\x07user_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n\x08provider\x18\x03 \x01(\tR\x08provider\x12\x1f\n\x0boccurred_at\x18\x04 \x01(\tR\noccurredAt\x12\x42\n\x0cmeasurements\x18\x05 \x03(\x0b\x32\x1e.photoops.usage.v1.MeasurementR\x0cmeasurements\x12%\n\x0e\x63orrelation_id\x18\x06 \x01(\tR\rcorrelationIdB\x8f\x01\n\x15\x63om.photoops.usage.v1B\x10\x43onsumptionProtoP\x01\xa2\x02\x03PUX\xaa\x02\x11Photoops.Usage.V1\xca\x02\x11Photoops\\Usage\\V1\xe2\x02\x1dPhotoops\\Usage\\V1\\GPBMetadata\xea\x02\x13Photoops::Usage::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usage.v1.consumption_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.photoops.usage.v1B\020ConsumptionProtoP\001\242\002\003PUX\252\002\021Photoops.Usage.V1\312\002\021Photoops\\Usage\\V1\342\002\035Photoops\\Usage\\V1\\GPBMetadata\352\002\023Photoops::Usage::V1'
  _globals['_MEASUREMENT']._serialized_start=50
  _globals['_MEASUREMENT']._serialized_end=267
  _globals['_CONSUMPTIONEVENT']._serialized_start=270
  _globals['_CONSUMPTIONEVENT']._serialized_end=522
# @@protoc_insertion_point(module_scope)
