// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: photo/v1/photo_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { HealthCheckRequest, HealthCheckResponse } from "../../common/v1/common";

export const protobufPackage = "photoops.photo.v1";

export enum PhotoStatus {
  PHOTO_STATUS_UNSPECIFIED = 0,
  PHOTO_STATUS_UPLOADING = 1,
  PHOTO_STATUS_UPLOADED = 2,
  PHOTO_STATUS_PROCESSING = 3,
  PHOTO_STATUS_READY = 4,
  PHOTO_STATUS_FAILED = 5,
  UNRECOGNIZED = -1,
}

export interface CreateUploadIntentRequest {
  filename: string;
  contentType: string;
  sizeBytes: string;
  userId: string;
}

export interface CreateUploadIntentResponse {
  photoId: string;
  objectKey: string;
  uploadUrl: string;
  expiresAt: string;
}

export interface CompleteUploadRequest {
  photoId: string;
  userId: string;
}

export interface ListPhotosRequest {
  pageSize: number;
  pageToken: string;
  userId: string;
}

export interface ListPhotosResponse {
  photos: PhotoAsset[];
  nextPageToken: string;
}

export interface PhotoAsset {
  id: string;
  filename: string;
  contentType: string;
  sizeBytes: string;
  objectKey: string;
  status: PhotoStatus;
  createdAt: string;
  updatedAt: string;
  userId: string;
}

export const PHOTOOPS_PHOTO_V1_PACKAGE_NAME = "photoops.photo.v1";

function createBaseCreateUploadIntentRequest(): CreateUploadIntentRequest {
  return { filename: "", contentType: "", sizeBytes: "", userId: "" };
}

export const CreateUploadIntentRequest: MessageFns<CreateUploadIntentRequest> = {
  encode(message: CreateUploadIntentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.filename !== "") {
      writer.uint32(10).string(message.filename);
    }
    if (message.contentType !== "") {
      writer.uint32(18).string(message.contentType);
    }
    if (message.sizeBytes !== "") {
      writer.uint32(26).string(message.sizeBytes);
    }
    if (message.userId !== "") {
      writer.uint32(34).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateUploadIntentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateUploadIntentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.filename = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.contentType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sizeBytes = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCreateUploadIntentResponse(): CreateUploadIntentResponse {
  return { photoId: "", objectKey: "", uploadUrl: "", expiresAt: "" };
}

export const CreateUploadIntentResponse: MessageFns<CreateUploadIntentResponse> = {
  encode(message: CreateUploadIntentResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.photoId !== "") {
      writer.uint32(10).string(message.photoId);
    }
    if (message.objectKey !== "") {
      writer.uint32(18).string(message.objectKey);
    }
    if (message.uploadUrl !== "") {
      writer.uint32(26).string(message.uploadUrl);
    }
    if (message.expiresAt !== "") {
      writer.uint32(34).string(message.expiresAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateUploadIntentResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateUploadIntentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.photoId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.objectKey = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.uploadUrl = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.expiresAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCompleteUploadRequest(): CompleteUploadRequest {
  return { photoId: "", userId: "" };
}

export const CompleteUploadRequest: MessageFns<CompleteUploadRequest> = {
  encode(message: CompleteUploadRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.photoId !== "") {
      writer.uint32(10).string(message.photoId);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CompleteUploadRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCompleteUploadRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.photoId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseListPhotosRequest(): ListPhotosRequest {
  return { pageSize: 0, pageToken: "", userId: "" };
}

export const ListPhotosRequest: MessageFns<ListPhotosRequest> = {
  encode(message: ListPhotosRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pageSize !== 0) {
      writer.uint32(8).int32(message.pageSize);
    }
    if (message.pageToken !== "") {
      writer.uint32(18).string(message.pageToken);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListPhotosRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListPhotosRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.pageSize = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pageToken = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseListPhotosResponse(): ListPhotosResponse {
  return { photos: [], nextPageToken: "" };
}

export const ListPhotosResponse: MessageFns<ListPhotosResponse> = {
  encode(message: ListPhotosResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.photos) {
      PhotoAsset.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.nextPageToken !== "") {
      writer.uint32(18).string(message.nextPageToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListPhotosResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListPhotosResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.photos.push(PhotoAsset.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nextPageToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBasePhotoAsset(): PhotoAsset {
  return {
    id: "",
    filename: "",
    contentType: "",
    sizeBytes: "",
    objectKey: "",
    status: 0,
    createdAt: "",
    updatedAt: "",
    userId: "",
  };
}

export const PhotoAsset: MessageFns<PhotoAsset> = {
  encode(message: PhotoAsset, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.filename !== "") {
      writer.uint32(18).string(message.filename);
    }
    if (message.contentType !== "") {
      writer.uint32(26).string(message.contentType);
    }
    if (message.sizeBytes !== "") {
      writer.uint32(34).string(message.sizeBytes);
    }
    if (message.objectKey !== "") {
      writer.uint32(42).string(message.objectKey);
    }
    if (message.status !== 0) {
      writer.uint32(48).int32(message.status);
    }
    if (message.createdAt !== "") {
      writer.uint32(58).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(66).string(message.updatedAt);
    }
    if (message.userId !== "") {
      writer.uint32(74).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PhotoAsset {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePhotoAsset();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.filename = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.contentType = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.sizeBytes = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.objectKey = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface PhotoServiceClient {
  health(request: HealthCheckRequest): Observable<HealthCheckResponse>;

  createUploadIntent(request: CreateUploadIntentRequest): Observable<CreateUploadIntentResponse>;

  completeUpload(request: CompleteUploadRequest): Observable<PhotoAsset>;

  listPhotos(request: ListPhotosRequest): Observable<ListPhotosResponse>;
}

export interface PhotoServiceController {
  health(
    request: HealthCheckRequest,
  ): Promise<HealthCheckResponse> | Observable<HealthCheckResponse> | HealthCheckResponse;

  createUploadIntent(
    request: CreateUploadIntentRequest,
  ): Promise<CreateUploadIntentResponse> | Observable<CreateUploadIntentResponse> | CreateUploadIntentResponse;

  completeUpload(request: CompleteUploadRequest): Promise<PhotoAsset> | Observable<PhotoAsset> | PhotoAsset;

  listPhotos(
    request: ListPhotosRequest,
  ): Promise<ListPhotosResponse> | Observable<ListPhotosResponse> | ListPhotosResponse;
}

export function PhotoServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["health", "createUploadIntent", "completeUpload", "listPhotos"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PhotoService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PhotoService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PHOTO_SERVICE_NAME = "PhotoService";

export type PhotoServiceService = typeof PhotoServiceService;
export const PhotoServiceService = {
  health: {
    path: "/photoops.photo.v1.PhotoService/Health" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HealthCheckRequest): Buffer => Buffer.from(HealthCheckRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HealthCheckRequest => HealthCheckRequest.decode(value),
    responseSerialize: (value: HealthCheckResponse): Buffer => Buffer.from(HealthCheckResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HealthCheckResponse => HealthCheckResponse.decode(value),
  },
  createUploadIntent: {
    path: "/photoops.photo.v1.PhotoService/CreateUploadIntent" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateUploadIntentRequest): Buffer =>
      Buffer.from(CreateUploadIntentRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateUploadIntentRequest => CreateUploadIntentRequest.decode(value),
    responseSerialize: (value: CreateUploadIntentResponse): Buffer =>
      Buffer.from(CreateUploadIntentResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateUploadIntentResponse => CreateUploadIntentResponse.decode(value),
  },
  completeUpload: {
    path: "/photoops.photo.v1.PhotoService/CompleteUpload" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CompleteUploadRequest): Buffer =>
      Buffer.from(CompleteUploadRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CompleteUploadRequest => CompleteUploadRequest.decode(value),
    responseSerialize: (value: PhotoAsset): Buffer => Buffer.from(PhotoAsset.encode(value).finish()),
    responseDeserialize: (value: Buffer): PhotoAsset => PhotoAsset.decode(value),
  },
  listPhotos: {
    path: "/photoops.photo.v1.PhotoService/ListPhotos" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListPhotosRequest): Buffer => Buffer.from(ListPhotosRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListPhotosRequest => ListPhotosRequest.decode(value),
    responseSerialize: (value: ListPhotosResponse): Buffer => Buffer.from(ListPhotosResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListPhotosResponse => ListPhotosResponse.decode(value),
  },
} as const;

export interface PhotoServiceServer extends UntypedServiceImplementation {
  health: handleUnaryCall<HealthCheckRequest, HealthCheckResponse>;
  createUploadIntent: handleUnaryCall<CreateUploadIntentRequest, CreateUploadIntentResponse>;
  completeUpload: handleUnaryCall<CompleteUploadRequest, PhotoAsset>;
  listPhotos: handleUnaryCall<ListPhotosRequest, ListPhotosResponse>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
