// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: photo/v1/photo_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { HealthCheckRequest, HealthCheckResponse } from "../../common/v1/common";

export const protobufPackage = "photoops.photo.v1";

export enum PhotoStatus {
  PHOTO_STATUS_UNSPECIFIED = 0,
  PHOTO_STATUS_UPLOADING = 1,
  PHOTO_STATUS_UPLOADED = 2,
  PHOTO_STATUS_PROCESSING = 3,
  PHOTO_STATUS_READY = 4,
  PHOTO_STATUS_FAILED = 5,
  UNRECOGNIZED = -1,
}

/** Sort key for ListPhotos. UNSPECIFIED is treated as CREATED_AT. */
export enum PhotoSortField {
  PHOTO_SORT_FIELD_UNSPECIFIED = 0,
  PHOTO_SORT_FIELD_CREATED_AT = 1,
  PHOTO_SORT_FIELD_TAKEN_AT = 2,
  PHOTO_SORT_FIELD_FILENAME = 3,
  PHOTO_SORT_FIELD_SIZE_BYTES = 4,
  UNRECOGNIZED = -1,
}

/** Sort direction for ListPhotos. UNSPECIFIED is treated as DESC. */
export enum SortDirection {
  SORT_DIRECTION_UNSPECIFIED = 0,
  SORT_DIRECTION_ASC = 1,
  SORT_DIRECTION_DESC = 2,
  UNRECOGNIZED = -1,
}

export interface CreateUploadIntentRequest {
  filename: string;
  contentType: string;
  sizeBytes: string;
  userId: string;
}

export interface CreateUploadIntentResponse {
  photoId: string;
  objectKey: string;
  uploadUrl: string;
  expiresAt: string;
}

export interface CompleteUploadRequest {
  photoId: string;
  userId: string;
}

export interface ListPhotosRequest {
  /** clamp 1..100; 0 -> default 24 */
  pageSize: number;
  userId: string;
  /** 1-based page; 0 -> default 1 */
  page: number;
  /** UNSPECIFIED -> created_at */
  sortBy: PhotoSortField;
  /** UNSPECIFIED -> desc */
  sortDir: SortDirection;
  /** empty -> all statuses */
  statusFilter: PhotoStatus[];
  /** empty -> no filter; case-insensitive substring on filename */
  filenameQuery: string;
}

export interface ListPhotosResponse {
  photos: PhotoAsset[];
  /** total rows matching the filter (for page N of M) */
  totalCount: number;
}

export interface GetPhotoRequest {
  photoId: string;
  userId: string;
}

/**
 * A generated variant rendition surfaced to the UI, with a short-lived,
 * owner-scoped presigned GET url.
 */
export interface PhotoVariantView {
  /** "thumbnail" | "preview" */
  variantType: string;
  url: string;
  width: number;
  height: number;
}

export interface PhotoAsset {
  id: string;
  filename: string;
  contentType: string;
  sizeBytes: string;
  objectKey: string;
  status: PhotoStatus;
  createdAt: string;
  updatedAt: string;
  userId: string;
  /** Extracted attributes (populated after processing; defaults/absent before). */
  width: number;
  height: number;
  /** tz-less wall-clock; "" if absent */
  takenAtLocal: string;
  /** explicit-UTC ISO instant; "" if unresolved */
  takenAtUtc: string;
  /** exif_offset | gps_time | unknown */
  takenAtTzSource: string;
  cameraMake: string;
  cameraModel: string;
  /** EXIF 1..8; 0 = absent */
  orientation: number;
  lat?: number | undefined;
  lon?: number | undefined;
  variants: PhotoVariantView[];
}

export const PHOTOOPS_PHOTO_V1_PACKAGE_NAME = "photoops.photo.v1";

function createBaseCreateUploadIntentRequest(): CreateUploadIntentRequest {
  return { filename: "", contentType: "", sizeBytes: "", userId: "" };
}

export const CreateUploadIntentRequest: MessageFns<CreateUploadIntentRequest> = {
  encode(message: CreateUploadIntentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.filename !== "") {
      writer.uint32(10).string(message.filename);
    }
    if (message.contentType !== "") {
      writer.uint32(18).string(message.contentType);
    }
    if (message.sizeBytes !== "") {
      writer.uint32(26).string(message.sizeBytes);
    }
    if (message.userId !== "") {
      writer.uint32(34).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateUploadIntentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateUploadIntentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.filename = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.contentType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sizeBytes = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCreateUploadIntentResponse(): CreateUploadIntentResponse {
  return { photoId: "", objectKey: "", uploadUrl: "", expiresAt: "" };
}

export const CreateUploadIntentResponse: MessageFns<CreateUploadIntentResponse> = {
  encode(message: CreateUploadIntentResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.photoId !== "") {
      writer.uint32(10).string(message.photoId);
    }
    if (message.objectKey !== "") {
      writer.uint32(18).string(message.objectKey);
    }
    if (message.uploadUrl !== "") {
      writer.uint32(26).string(message.uploadUrl);
    }
    if (message.expiresAt !== "") {
      writer.uint32(34).string(message.expiresAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateUploadIntentResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateUploadIntentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.photoId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.objectKey = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.uploadUrl = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.expiresAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCompleteUploadRequest(): CompleteUploadRequest {
  return { photoId: "", userId: "" };
}

export const CompleteUploadRequest: MessageFns<CompleteUploadRequest> = {
  encode(message: CompleteUploadRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.photoId !== "") {
      writer.uint32(10).string(message.photoId);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CompleteUploadRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCompleteUploadRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.photoId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseListPhotosRequest(): ListPhotosRequest {
  return { pageSize: 0, userId: "", page: 0, sortBy: 0, sortDir: 0, statusFilter: [], filenameQuery: "" };
}

export const ListPhotosRequest: MessageFns<ListPhotosRequest> = {
  encode(message: ListPhotosRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pageSize !== 0) {
      writer.uint32(8).int32(message.pageSize);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    if (message.page !== 0) {
      writer.uint32(32).int32(message.page);
    }
    if (message.sortBy !== 0) {
      writer.uint32(40).int32(message.sortBy);
    }
    if (message.sortDir !== 0) {
      writer.uint32(48).int32(message.sortDir);
    }
    writer.uint32(58).fork();
    for (const v of message.statusFilter) {
      writer.int32(v);
    }
    writer.join();
    if (message.filenameQuery !== "") {
      writer.uint32(66).string(message.filenameQuery);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListPhotosRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListPhotosRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.pageSize = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.sortBy = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.sortDir = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag === 56) {
            message.statusFilter.push(reader.int32() as any);

            continue;
          }

          if (tag === 58) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.statusFilter.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.filenameQuery = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseListPhotosResponse(): ListPhotosResponse {
  return { photos: [], totalCount: 0 };
}

export const ListPhotosResponse: MessageFns<ListPhotosResponse> = {
  encode(message: ListPhotosResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.photos) {
      PhotoAsset.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.totalCount !== 0) {
      writer.uint32(24).int32(message.totalCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListPhotosResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListPhotosResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.photos.push(PhotoAsset.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetPhotoRequest(): GetPhotoRequest {
  return { photoId: "", userId: "" };
}

export const GetPhotoRequest: MessageFns<GetPhotoRequest> = {
  encode(message: GetPhotoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.photoId !== "") {
      writer.uint32(10).string(message.photoId);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPhotoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPhotoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.photoId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBasePhotoVariantView(): PhotoVariantView {
  return { variantType: "", url: "", width: 0, height: 0 };
}

export const PhotoVariantView: MessageFns<PhotoVariantView> = {
  encode(message: PhotoVariantView, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.variantType !== "") {
      writer.uint32(10).string(message.variantType);
    }
    if (message.url !== "") {
      writer.uint32(18).string(message.url);
    }
    if (message.width !== 0) {
      writer.uint32(24).uint32(message.width);
    }
    if (message.height !== 0) {
      writer.uint32(32).uint32(message.height);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PhotoVariantView {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePhotoVariantView();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.variantType = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.width = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.height = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBasePhotoAsset(): PhotoAsset {
  return {
    id: "",
    filename: "",
    contentType: "",
    sizeBytes: "",
    objectKey: "",
    status: 0,
    createdAt: "",
    updatedAt: "",
    userId: "",
    width: 0,
    height: 0,
    takenAtLocal: "",
    takenAtUtc: "",
    takenAtTzSource: "",
    cameraMake: "",
    cameraModel: "",
    orientation: 0,
    variants: [],
  };
}

export const PhotoAsset: MessageFns<PhotoAsset> = {
  encode(message: PhotoAsset, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.filename !== "") {
      writer.uint32(18).string(message.filename);
    }
    if (message.contentType !== "") {
      writer.uint32(26).string(message.contentType);
    }
    if (message.sizeBytes !== "") {
      writer.uint32(34).string(message.sizeBytes);
    }
    if (message.objectKey !== "") {
      writer.uint32(42).string(message.objectKey);
    }
    if (message.status !== 0) {
      writer.uint32(48).int32(message.status);
    }
    if (message.createdAt !== "") {
      writer.uint32(58).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(66).string(message.updatedAt);
    }
    if (message.userId !== "") {
      writer.uint32(74).string(message.userId);
    }
    if (message.width !== 0) {
      writer.uint32(80).uint32(message.width);
    }
    if (message.height !== 0) {
      writer.uint32(88).uint32(message.height);
    }
    if (message.takenAtLocal !== "") {
      writer.uint32(98).string(message.takenAtLocal);
    }
    if (message.takenAtUtc !== "") {
      writer.uint32(106).string(message.takenAtUtc);
    }
    if (message.takenAtTzSource !== "") {
      writer.uint32(114).string(message.takenAtTzSource);
    }
    if (message.cameraMake !== "") {
      writer.uint32(122).string(message.cameraMake);
    }
    if (message.cameraModel !== "") {
      writer.uint32(130).string(message.cameraModel);
    }
    if (message.orientation !== 0) {
      writer.uint32(136).uint32(message.orientation);
    }
    if (message.lat !== undefined) {
      writer.uint32(145).double(message.lat);
    }
    if (message.lon !== undefined) {
      writer.uint32(153).double(message.lon);
    }
    for (const v of message.variants) {
      PhotoVariantView.encode(v!, writer.uint32(162).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PhotoAsset {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePhotoAsset();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.filename = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.contentType = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.sizeBytes = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.objectKey = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.width = reader.uint32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.height = reader.uint32();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.takenAtLocal = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.takenAtUtc = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.takenAtTzSource = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.cameraMake = reader.string();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.cameraModel = reader.string();
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.orientation = reader.uint32();
          continue;
        }
        case 18: {
          if (tag !== 145) {
            break;
          }

          message.lat = reader.double();
          continue;
        }
        case 19: {
          if (tag !== 153) {
            break;
          }

          message.lon = reader.double();
          continue;
        }
        case 20: {
          if (tag !== 162) {
            break;
          }

          message.variants.push(PhotoVariantView.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface PhotoServiceClient {
  health(request: HealthCheckRequest): Observable<HealthCheckResponse>;

  createUploadIntent(request: CreateUploadIntentRequest): Observable<CreateUploadIntentResponse>;

  completeUpload(request: CompleteUploadRequest): Observable<PhotoAsset>;

  listPhotos(request: ListPhotosRequest): Observable<ListPhotosResponse>;

  getPhoto(request: GetPhotoRequest): Observable<PhotoAsset>;
}

export interface PhotoServiceController {
  health(
    request: HealthCheckRequest,
  ): Promise<HealthCheckResponse> | Observable<HealthCheckResponse> | HealthCheckResponse;

  createUploadIntent(
    request: CreateUploadIntentRequest,
  ): Promise<CreateUploadIntentResponse> | Observable<CreateUploadIntentResponse> | CreateUploadIntentResponse;

  completeUpload(request: CompleteUploadRequest): Promise<PhotoAsset> | Observable<PhotoAsset> | PhotoAsset;

  listPhotos(
    request: ListPhotosRequest,
  ): Promise<ListPhotosResponse> | Observable<ListPhotosResponse> | ListPhotosResponse;

  getPhoto(request: GetPhotoRequest): Promise<PhotoAsset> | Observable<PhotoAsset> | PhotoAsset;
}

export function PhotoServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["health", "createUploadIntent", "completeUpload", "listPhotos", "getPhoto"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PhotoService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PhotoService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PHOTO_SERVICE_NAME = "PhotoService";

export type PhotoServiceService = typeof PhotoServiceService;
export const PhotoServiceService = {
  health: {
    path: "/photoops.photo.v1.PhotoService/Health" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HealthCheckRequest): Buffer => Buffer.from(HealthCheckRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HealthCheckRequest => HealthCheckRequest.decode(value),
    responseSerialize: (value: HealthCheckResponse): Buffer => Buffer.from(HealthCheckResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HealthCheckResponse => HealthCheckResponse.decode(value),
  },
  createUploadIntent: {
    path: "/photoops.photo.v1.PhotoService/CreateUploadIntent" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateUploadIntentRequest): Buffer =>
      Buffer.from(CreateUploadIntentRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateUploadIntentRequest => CreateUploadIntentRequest.decode(value),
    responseSerialize: (value: CreateUploadIntentResponse): Buffer =>
      Buffer.from(CreateUploadIntentResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateUploadIntentResponse => CreateUploadIntentResponse.decode(value),
  },
  completeUpload: {
    path: "/photoops.photo.v1.PhotoService/CompleteUpload" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CompleteUploadRequest): Buffer =>
      Buffer.from(CompleteUploadRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CompleteUploadRequest => CompleteUploadRequest.decode(value),
    responseSerialize: (value: PhotoAsset): Buffer => Buffer.from(PhotoAsset.encode(value).finish()),
    responseDeserialize: (value: Buffer): PhotoAsset => PhotoAsset.decode(value),
  },
  listPhotos: {
    path: "/photoops.photo.v1.PhotoService/ListPhotos" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListPhotosRequest): Buffer => Buffer.from(ListPhotosRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListPhotosRequest => ListPhotosRequest.decode(value),
    responseSerialize: (value: ListPhotosResponse): Buffer => Buffer.from(ListPhotosResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListPhotosResponse => ListPhotosResponse.decode(value),
  },
  getPhoto: {
    path: "/photoops.photo.v1.PhotoService/GetPhoto" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetPhotoRequest): Buffer => Buffer.from(GetPhotoRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetPhotoRequest => GetPhotoRequest.decode(value),
    responseSerialize: (value: PhotoAsset): Buffer => Buffer.from(PhotoAsset.encode(value).finish()),
    responseDeserialize: (value: Buffer): PhotoAsset => PhotoAsset.decode(value),
  },
} as const;

export interface PhotoServiceServer extends UntypedServiceImplementation {
  health: handleUnaryCall<HealthCheckRequest, HealthCheckResponse>;
  createUploadIntent: handleUnaryCall<CreateUploadIntentRequest, CreateUploadIntentResponse>;
  completeUpload: handleUnaryCall<CompleteUploadRequest, PhotoAsset>;
  listPhotos: handleUnaryCall<ListPhotosRequest, ListPhotosResponse>;
  getPhoto: handleUnaryCall<GetPhotoRequest, PhotoAsset>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
