// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: photo/v1/processing.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "photoops.photo.v1";

/** How a processing run was initiated. */
export enum ProcessingType {
  PROCESSING_TYPE_UNSPECIFIED = 0,
  PROCESSING_TYPE_INITIAL = 1,
  /** PROCESSING_TYPE_REPROCESS - Seam only; not emitted in session 008. Reserved for user-initiated reprocess. */
  PROCESSING_TYPE_REPROCESS = 2,
  UNRECOGNIZED = -1,
}

/** Terminal outcome of a processing run. */
export enum ProcessingOutcome {
  PROCESSING_OUTCOME_UNSPECIFIED = 0,
  PROCESSING_OUTCOME_SUCCEEDED = 1,
  PROCESSING_OUTCOME_FAILED = 2,
  UNRECOGNIZED = -1,
}

/** Job published by photo-service when an upload completes; consumed by media-worker. */
export interface ProcessPhotoJob {
  /** UUID v7, == ProcessingJob.id (idempotency key) */
  jobId: string;
  photoId: string;
  userId: string;
  /** original's MinIO object key */
  objectKey: string;
  type: ProcessingType;
  /** threaded through logs/trace; not an idempotency key */
  correlationId: string;
}

/** Extracted image attributes. Dimensions are oriented (as displayed). */
export interface ImageAttributes {
  width: number;
  height: number;
  /** ISO local wall-clock, no tz; "" if absent */
  takenAtLocal: string;
  /** ISO instant; "" if unresolved */
  takenAtUtc: string;
  /** "exif_offset" | "gps_time" | "unknown" */
  takenAtTzSource: string;
  cameraMake: string;
  cameraModel: string;
  /** EXIF orientation 1..8; 0 = absent */
  orientation: number;
  lat?: number | undefined;
  lon?: number | undefined;
}

/** One generated variant produced by a processing run. */
export interface VariantResult {
  /** "thumbnail" | "preview" */
  variantType: string;
  objectKey: string;
  width: number;
  height: number;
  sizeBytes: string;
  contentType: string;
}

/** Result published by media-worker; consumed by photo-service to finalize. */
export interface PhotoProcessingResult {
  jobId: string;
  photoId: string;
  correlationId: string;
  outcome: ProcessingOutcome;
  /** when FAILED */
  errorMessage: string;
  /** when SUCCEEDED */
  attributes: ImageAttributes | undefined;
  variants: VariantResult[];
  /** sanitized raw EXIF as a JSON string */
  metadataJson: string;
}

export const PHOTOOPS_PHOTO_V1_PACKAGE_NAME = "photoops.photo.v1";

function createBaseProcessPhotoJob(): ProcessPhotoJob {
  return { jobId: "", photoId: "", userId: "", objectKey: "", type: 0, correlationId: "" };
}

export const ProcessPhotoJob: MessageFns<ProcessPhotoJob> = {
  encode(message: ProcessPhotoJob, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.photoId !== "") {
      writer.uint32(18).string(message.photoId);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    if (message.objectKey !== "") {
      writer.uint32(34).string(message.objectKey);
    }
    if (message.type !== 0) {
      writer.uint32(40).int32(message.type);
    }
    if (message.correlationId !== "") {
      writer.uint32(50).string(message.correlationId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProcessPhotoJob {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProcessPhotoJob();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.photoId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.objectKey = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.correlationId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseImageAttributes(): ImageAttributes {
  return {
    width: 0,
    height: 0,
    takenAtLocal: "",
    takenAtUtc: "",
    takenAtTzSource: "",
    cameraMake: "",
    cameraModel: "",
    orientation: 0,
  };
}

export const ImageAttributes: MessageFns<ImageAttributes> = {
  encode(message: ImageAttributes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.width !== 0) {
      writer.uint32(8).uint32(message.width);
    }
    if (message.height !== 0) {
      writer.uint32(16).uint32(message.height);
    }
    if (message.takenAtLocal !== "") {
      writer.uint32(26).string(message.takenAtLocal);
    }
    if (message.takenAtUtc !== "") {
      writer.uint32(34).string(message.takenAtUtc);
    }
    if (message.takenAtTzSource !== "") {
      writer.uint32(42).string(message.takenAtTzSource);
    }
    if (message.cameraMake !== "") {
      writer.uint32(50).string(message.cameraMake);
    }
    if (message.cameraModel !== "") {
      writer.uint32(58).string(message.cameraModel);
    }
    if (message.orientation !== 0) {
      writer.uint32(64).uint32(message.orientation);
    }
    if (message.lat !== undefined) {
      writer.uint32(73).double(message.lat);
    }
    if (message.lon !== undefined) {
      writer.uint32(81).double(message.lon);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ImageAttributes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseImageAttributes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.width = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.height = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.takenAtLocal = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.takenAtUtc = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.takenAtTzSource = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.cameraMake = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.cameraModel = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.orientation = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 73) {
            break;
          }

          message.lat = reader.double();
          continue;
        }
        case 10: {
          if (tag !== 81) {
            break;
          }

          message.lon = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseVariantResult(): VariantResult {
  return { variantType: "", objectKey: "", width: 0, height: 0, sizeBytes: "0", contentType: "" };
}

export const VariantResult: MessageFns<VariantResult> = {
  encode(message: VariantResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.variantType !== "") {
      writer.uint32(10).string(message.variantType);
    }
    if (message.objectKey !== "") {
      writer.uint32(18).string(message.objectKey);
    }
    if (message.width !== 0) {
      writer.uint32(24).uint32(message.width);
    }
    if (message.height !== 0) {
      writer.uint32(32).uint32(message.height);
    }
    if (message.sizeBytes !== "0") {
      writer.uint32(40).uint64(message.sizeBytes);
    }
    if (message.contentType !== "") {
      writer.uint32(50).string(message.contentType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VariantResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVariantResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.variantType = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.objectKey = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.width = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.height = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.sizeBytes = reader.uint64().toString();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.contentType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBasePhotoProcessingResult(): PhotoProcessingResult {
  return {
    jobId: "",
    photoId: "",
    correlationId: "",
    outcome: 0,
    errorMessage: "",
    attributes: undefined,
    variants: [],
    metadataJson: "",
  };
}

export const PhotoProcessingResult: MessageFns<PhotoProcessingResult> = {
  encode(message: PhotoProcessingResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.photoId !== "") {
      writer.uint32(18).string(message.photoId);
    }
    if (message.correlationId !== "") {
      writer.uint32(26).string(message.correlationId);
    }
    if (message.outcome !== 0) {
      writer.uint32(32).int32(message.outcome);
    }
    if (message.errorMessage !== "") {
      writer.uint32(42).string(message.errorMessage);
    }
    if (message.attributes !== undefined) {
      ImageAttributes.encode(message.attributes, writer.uint32(50).fork()).join();
    }
    for (const v of message.variants) {
      VariantResult.encode(v!, writer.uint32(58).fork()).join();
    }
    if (message.metadataJson !== "") {
      writer.uint32(66).string(message.metadataJson);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PhotoProcessingResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePhotoProcessingResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.photoId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.correlationId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.outcome = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.attributes = ImageAttributes.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.variants.push(VariantResult.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.metadataJson = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
